# Generated by Django 4.2.23 on 2025-09-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname_or_companyname', models.CharField(max_length=255)),
                ('care_of', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('notes_or_remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
    ]
