"""
Django settings for autocad_system project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(em#dzjtz^ks6k)3lak01fv6--oi#!1&tydd$2%z*)$9af(ff('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'customer',
    'monitoring',
    'channels',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'autocad_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autocad_system.wsgi.application'

ASGI_APPLICATION = "autocad_system.asgi.application"

# For production use Redis. For quick dev you can set CHANNEL_LAYERS to in-memory, but Redis recommended:
CHANNEL_LAYERS = {
    "default": {
        # Redis (recommended)
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    }
}
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
#STATICFILES_DIRS = [
#    BASE_DIR / "static",
#]

STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "AutoCad System Admin",
    "site_header": "AutoCad System",
    "site_brand": "AutoCad Mgt.",
    "welcome_sign": "Welcome to Autocad Admin Panel",
    "copyright": "Saitech | AutoCAD System 2025",
    "site_logo": "customer/img/saitechweb.png",
    "site_logo_classes": "img-circle",
    "custom_css": "customer/css/custom.css",
    "custom_js": [
        "chat/js/chat.js",
    ],

    # ✅ Order apps properly
    "order_with_respect_to": ["auth", "monitoring", "customer"],

    # ✅ Add your Archives link as a custom link
    "custom_links": {
                        "monitoring": [
                            {
                                "name": "Archives",
                                "url": "admin:archive_months",  # ✅ FIXED
                                "icon": "fas fa-archive",
                                "permissions": ["monitoring.view_panelrecord"],
                            },
                        ],
                    },

    "icons": {
        "customer": "fas fa-desktop",
        "customer.Customer": "fas fa-user",
        "customer.Sender": "fas fa-paper-plane",
        "monitoring": "fas fa-desktop",
        "monitoring.PanelRecord": "fas fa-columns",
    },

    "navigation_expanded": True,
    "show_sidebar": True,
}


JAZZMIN_UI_TWEAKS = {
    "theme": "cosmo",
    "navbar": "navbar-dark navbar-primary",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_flat_style": True,
    "sidebar_fixed": True,
    "navbar_fixed": True,
    "footer_fixed": False,
}
