# Generated by Django 4.2.23 on 2025-09-15 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PanelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fq_number', models.CharField(max_length=50)),
                ('jo_number', models.CharField(max_length=50)),
                ('panel_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('received_by', models.CharField(max_length=100)),
                ('box_type', models.CharField(choices=[('nema1', 'NEMA 1'), ('nema3r', 'NEMA 3R'), ('nema12', 'NEMA 12'), ('nema4x', 'NEMA 4X'), ('itemonly', 'Item Only'), ('others', 'Others')], max_length=20)),
                ('main_cb', models.CharField(max_length=100)),
                ('cb_model', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('gray_wrinkle', 'Gray Wrinkle'), ('beige_wrinkle', 'Beige Wrinkle'), ('stainless_steel', 'Stainless Steel'), ('item_only', 'Item Only'), ('others', 'Others')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='monitoring.panel')),
            ],
        ),
    ]
