# Generated by Django 4.2.23 on 2025-09-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelrecord',
            name='panel',
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
    ]
