# Generated by Django 5.2.6 on 2025-10-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_panelrecord_panel_delete_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelrecord',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
