# Generated by Django 5.2.6 on 2025-11-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_panelrecord_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelrecord',
            name='color',
            field=models.CharField(choices=[('gray_wrinkle', 'Gray Wrinkle'), ('beige_wrinkle', 'Beige Wrinkle'), ('black_wrinkle', 'Black Wrinkle'), ('blue_wrinkle', 'Blue Wrinkle'), ('green_wrinkle', 'Green Wrinkle'), ('light_gray_wrinkle', 'Red Wrinkle'), ('orange_wrinkle', 'Orange Wrinkle'), ('red_wrinkle', 'Red Wrinkle'), ('white_wrinkle', 'White Wrinkle'), ('yellow_wrinkle', 'Yellow Wrinkle'), ('stainless_steel', 'Stainless Steel'), ('item_only', 'Item Only'), ('others', 'Others')], max_length=20),
        ),
    ]
